services:
  minecraft:
    image: itzg/minecraft-server:java21
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "4G"
      ENABLE_RCON: "false"
      CREATE_CONSOLE_IN_PIPE: "true"
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
    ports:
      - "25565:25565"
    volumes:
      - mcdata:/data
      - ./plugins:/plugins:ro
      - ./configs/LuckPerms/config.yml:/data/plugins/LuckPerms/config.yml:ro
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mc-monitor", "status", "--host", "localhost", "--port", "25565"]
      interval: 30s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mc_pass}
      POSTGRES_DB: ${POSTGRES_DB:-minecraft}
      TZ: "Europe/Paris"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mc_user -d minecraft" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mcdata:
  postgres-data:
