services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "4G"
      ENABLE_RCON: "false"
    ports:
      - "25565:25565"
    volumes:
      - mcdata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-monitor", "status", "--host", "localhost", "--port", "25565"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  mcdata:
