services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.6"
      MEMORY: "4G"
      ENABLE_RCON: "false"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
